#!/usr/bin/env ruby

require 'rubygems'
require 'optparse'
require 'open-uri'
require 'json'

#---------------------------------------------------------------
# listmovies - prints out the list of movies
#---------------------------------------------------------------
def get_user_selection( movies )
	good_input = false
	selection = -1

	until good_input
		movies.keys.sort.each do |key|
			puts "#{key} #{movies[key]}"
		end

		print "Which movie do you want to watch (enter the number or q to quit)? "
		selection = gets.chomp

		if selection == "q"
			exit
		end

		if movies.has_key? selection.to_i
			good_input = true
		end
	end

	return movies[selection.to_i]
end

#---------------------------------------------------------------
# parses command line option
#---------------------------------------------------------------

options = {}

optparse = OptionParser.new do |opts|

	opts.banner = "Usage: movieplay [options]"

	options[:server] = "127.0.0.1"
	opts.on('-s', '--server SERVER', 'Movie Server') do |s|
		options[:server] = s
	end

	options[:type] = "mp4"
	opts.on('-t', '--type TYPE', 'Video Type') do |t|
		options[:type] = t
	end

	options[:port] = "8080"
	opts.on('-p', '--port PORT', 'Port') do |p|
		options[:port] = p
	end

	opts.on('-h', '--help', 'Display this screen') do
		puts opts
		exit
	end
end

optparse.parse!

#---------------------------------------------------------------
# connect to server and parse xml
#---------------------------------------------------------------

connection = "http://#{options[:server]}:#{options[:port]}/movielist"

begin
    url = open( connection ).read
    movies = JSON.parse( url )
rescue Exception => e
    puts "Exception Occured: #{e}"
    exit 1
end


movie_choices  = Hash.new
type = ".#{options[:type]}"

i = 1
movies.each do | vid |
    if File.extname( vid ) == type
        movie_choices[i] = vid
        i += 1
    end
end

#---------------------------------------------------------------
# get selection from the user and play movie via ffplay on obsd,
# open on macosx
#---------------------------------------------------------------

film = get_user_selection movie_choices

file_path = "http://#{options[:server]}:#{options[:port]}/#{film}"

if RUBY_PLATFORM =~ /darwin/
	system("open #{file_path}")
elsif RUBY_PLATFORM =~ /linux/
	system("totem #{file_path}")
else
	system("ffplay #{file_path}")
end
