#!/usr/bin/env ruby

require 'rubygems'
require 'optparse'
require 'open-uri'
require 'nokogiri'

options = {}

optparse = OptionParser.new do |opts|

	opts.banner = "Usage: movieplay [options]"

	options[:server] = "127.0.0.1"
	opts.on('-s', '--server SERVER', 'Movie Server') do |s|
		options[:server] = s
	end

	options[:type] = "mp4"
	opts.on('-t', '--type TYPE', 'Video Type') do |t|
		options[:type] = t
	end

	options[:port] = "8080"
	opts.on('-p', '--port PORT', 'Port') do |p|
		options[:port] = p
	end

	opts.on('-h', '--help', 'Display this screen') do
		puts opts
		exit
	end
end

optparse.parse!

connection = "http://#{options[:server]}:#{options[:port]}/movielist"

doc = Nokogiri::XML(open(connection)) do |config|
	config.strict
end

css = "#{options[:type]} title"

movie_dict = Hash.new

i = 1
doc.css(css).each do |title|
	puts i.to_s + " " + title.content
	movie_dict[i.to_s] = title.content
	i += 1
end

print "Which movie do you want to watch (enter the number)?"
selection = gets.chomp

file_path = "http://#{options[:server]}:#{options[:port]}/#{movie_dict[selection]}"

puts file_path

system("ffplay #{file_path}")
