#!/usr/bin/env ruby

#---------------------------------------------------------------
#
# Michael B. Kulik
# 05/08/2012
#
# 
#
#
#---------------------------------------------------------------

require 'rubygems'
require 'optparse'
require 'open-uri'
require 'json'

#---------------------------------------------------------------
# get_user_selection - returns the movie the user wants to watch
# or quits the program
#---------------------------------------------------------------
def get_user_selection( movies )
	good_input = false
	selection = -1

	until good_input
		movies.keys.sort.each do |key|
			puts "#{key} #{movies[key]}"
		end

		print "Which movie do you want to watch (enter the number or q to quit)? "
		selection = gets.chomp

		if selection == "q"
			exit
		end

		if movies.has_key? selection.to_i
			good_input = true
		end
	end

	return movies[selection.to_i]
end

#---------------------------------------------------------------
# parses command line option
#---------------------------------------------------------------

options = {}

optparse = OptionParser.new do |opts|

	opts.banner = "Usage: movieplay [options]"

	options[:server] = "127.0.0.1"
	opts.on('-s', '--server SERVER', 'Movie Server') do |s|
		options[:server] = s
	end

	options[:type] = "mp4"
	opts.on('-t', '--type TYPE', 'Video Type') do |t|
		options[:type] = t
	end

	options[:port] = "8080"
	opts.on('-p', '--port PORT', 'Port') do |p|
		options[:port] = p
	end

	opts.on('-h', '--help', 'Display this screen') do
		puts opts
		exit
	end
end

optparse.parse!

#---------------------------------------------------------------
# connect to server retrieves the list of movies in JSON
#---------------------------------------------------------------

connection = "http://#{options[:server]}:#{options[:port]}/movielist"

begin
    url = open( connection ).read
    movies = JSON.parse( url )
rescue Exception => e
    puts "Exception Occured: #{e}"
    exit 1
end


movie_choices  = Hash.new
type = ".#{options[:type]}"

i = 1
movies.each do | vid |
    if File.extname( vid ) == type
        movie_choices[i] = vid
        i += 1
    end
end

#---------------------------------------------------------------
# get selection from the user and plays the movie
#
# uses VLC on OS X or falls back on open command
# uses totem on linux
# uses ffplay on everything else
#---------------------------------------------------------------

film = get_user_selection movie_choices

file_path = "http://#{options[:server]}:#{options[:port]}/#{film}"

if RUBY_PLATFORM =~ /darwin/

    if File.exists?("/Applications/VLC.app/")
        system("open /Applications/VLC.app/ --args #{file_path}")
    else
        system("open #{file_path}")
    end
    
elsif RUBY_PLATFORM =~ /linux/
	system("totem #{file_path}")

else
	system("ffplay #{file_path}")
end
